apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgICAgICAgImdoY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWW1sdVlYSnBiRHBuYUhCZmJFWlNOVXRhWmtwV2JEQnhkRnB3Y1hWek9XRkRORFZpYm1OT1dsUk5NMVYyWkUxdCIKICAgICAgICAgICAgICAgIH0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
